version: "3"
services:
  db:
    image: "mysql:5.7"
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: micro_posts
      MYSQL_USER: micro_posts
      MYSQL_PASSWORD: pass
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
  web:
    image: "nginx:1.15"
    ports:
      - "80:80"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
