version: "3"
services:
  db:
    image: "mysql:5.7"
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: micro_posts
      MYSQL_USER: micro_posts
      MYSQL_PASSWORD: pass
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"